
cc_binary(
    name = "solution",
    srcs = ["main.cc",
            ],
    deps = [
        ":max_points_on_a_line",
    ],
)

cc_library(
    name = "max_points_on_a_line",
    hdrs = [ "max_points_on_a_line.h",
    ],
    srcs = [ "max_points_on_a_line.cc",
    ],
)
