
cc_library(
    name = "point",
    hdrs = [ "point.h",],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "list_node",
    hdrs = [ "list_node.h",],
    visibility = ["//visibility:public"],
)

